<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Product Plan Feature Matrix
    |--------------------------------------------------------------------------
    |
    | Each product key maps to its plan tiers. Each tier defines feature flags
    | (boolean) and numeric limits (null = unlimited). The PlanService reads
    | this config to enforce gating throughout the application.
    |
    */

    'board' => [
        'free' => [
            'max_boards' => 5,
            'max_members' => 10,
            'custom_fields' => false,
            'automations' => false,
            'templates' => false,
            'board_chat' => true,
            'calendar_view' => true,
            'timeline_view' => false,
            'dashboard_view' => false,
        ],
        'pro' => [
            'max_boards' => 50,
            'max_members' => 100,
            'custom_fields' => true,
            'automations' => true,
            'templates' => true,
            'board_chat' => true,
            'calendar_view' => true,
            'timeline_view' => true,
            'dashboard_view' => true,
        ],
        'enterprise' => [
            'max_boards' => null,
            'max_members' => null,
            'custom_fields' => true,
            'automations' => true,
            'templates' => true,
            'board_chat' => true,
            'calendar_view' => true,
            'timeline_view' => true,
            'dashboard_view' => true,
        ],
    ],

    'projects' => [
        'free' => [
            'max_projects' => 3,
            'max_members' => 10,
            'sprints' => false,
            'time_tracking' => true,
            'timesheets' => false,
            'billing' => false,
            'custom_fields' => false,
            'recurring_tasks' => false,
            'documents' => true,
            'budget' => false,
            'workload' => false,
        ],
        'pro' => [
            'max_projects' => 50,
            'max_members' => 100,
            'sprints' => true,
            'time_tracking' => true,
            'timesheets' => true,
            'billing' => true,
            'custom_fields' => true,
            'recurring_tasks' => true,
            'documents' => true,
            'budget' => true,
            'workload' => true,
        ],
        'enterprise' => [
            'max_projects' => null,
            'max_members' => null,
            'sprints' => true,
            'time_tracking' => true,
            'timesheets' => true,
            'billing' => true,
            'custom_fields' => true,
            'recurring_tasks' => true,
            'documents' => true,
            'budget' => true,
            'workload' => true,
        ],
    ],

    'opportunity' => [
        'free' => [
            'max_projects' => 5,
            'max_members' => 15,
            'goals' => false,
            'portfolios' => false,
            'reporting' => false,
            'forms' => true,
            'automations' => false,
            'templates' => false,
            'approvals' => false,
        ],
        'pro' => [
            'max_projects' => 50,
            'max_members' => 100,
            'goals' => true,
            'portfolios' => true,
            'reporting' => true,
            'forms' => true,
            'automations' => true,
            'templates' => true,
            'approvals' => true,
        ],
        'enterprise' => [
            'max_projects' => null,
            'max_members' => null,
            'goals' => true,
            'portfolios' => true,
            'reporting' => true,
            'forms' => true,
            'automations' => true,
            'templates' => true,
            'approvals' => true,
        ],
    ],

    'hr' => [
        'free' => [
            'max_employees' => 25,
            'attendance' => true,
            'leave' => true,
            'payroll' => false,
            'performance' => false,
            'expenses' => false,
            'recruitment' => false,
            'surveys' => false,
            'announcements' => true,
            'engagement' => true,
            'onboarding' => false,
        ],
        'pro' => [
            'max_employees' => 250,
            'attendance' => true,
            'leave' => true,
            'payroll' => true,
            'performance' => true,
            'expenses' => true,
            'recruitment' => true,
            'surveys' => true,
            'announcements' => true,
            'engagement' => true,
            'onboarding' => true,
        ],
        'enterprise' => [
            'max_employees' => null,
            'attendance' => true,
            'leave' => true,
            'payroll' => true,
            'performance' => true,
            'expenses' => true,
            'recruitment' => true,
            'surveys' => true,
            'announcements' => true,
            'engagement' => true,
            'onboarding' => true,
        ],
    ],

    'docs' => [
        'free' => [
            'max_documents' => 25,
            'max_folders' => 10,
            'max_storage_mb' => 100,
            'fulltext_search' => true,
            'version_history' => true,
            'sharing' => true,
            'forms' => true,
            'form_responses_per_form' => 100,
            'spreadsheets' => true,
            'presentations' => true,
            'comments' => false,
            'templates' => false,
        ],
        'pro' => [
            'max_documents' => 500,
            'max_folders' => 100,
            'max_storage_mb' => 5120,
            'fulltext_search' => true,
            'version_history' => true,
            'sharing' => true,
            'forms' => true,
            'form_responses_per_form' => null,
            'spreadsheets' => true,
            'presentations' => true,
            'comments' => true,
            'templates' => true,
        ],
        'enterprise' => [
            'max_documents' => null,
            'max_folders' => null,
            'max_storage_mb' => null,
            'fulltext_search' => true,
            'version_history' => true,
            'sharing' => true,
            'forms' => true,
            'form_responses_per_form' => null,
            'spreadsheets' => true,
            'presentations' => true,
            'comments' => true,
            'templates' => true,
        ],
    ],

    'knowledge_base' => [
        'free' => [
            'max_categories' => 20,
            'max_articles' => 100,
            'max_storage_mb' => 250,
            'revision_history' => true,
            'attachments' => true,
            'fulltext_search' => true,
        ],
        'pro' => [
            'max_categories' => 200,
            'max_articles' => 5000,
            'max_storage_mb' => 5120,
            'revision_history' => true,
            'attachments' => true,
            'fulltext_search' => true,
        ],
        'enterprise' => [
            'max_categories' => null,
            'max_articles' => null,
            'max_storage_mb' => null,
            'revision_history' => true,
            'attachments' => true,
            'fulltext_search' => true,
        ],
    ],

];
